// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccessLayer.Entity
{
    public partial class Adresse
    {
        public Adresse()
        {
            Personne = new HashSet<Personne>();
        }

        [Key]
        public long Id { get; set; }
        [Column(TypeName = "VARCHAR (200)")]
        public string Libelle { get; set; }
        [Column(TypeName = "VARCHAR (5)")]
        public string CodePostal { get; set; }

        [InverseProperty("IdAdresseNavigation")]
        public virtual ICollection<Personne> Personne { get; set; }
    }
}