// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccessLayer.Entity
{
    [Keyless]
    public partial class User
    {
        public int? Id { get; set; }
        [StringLength(200)]
        public string Nom { get; set; }
        [StringLength(200)]
        public string Prenom { get; set; }
        public int? Age { get; set; }
    }
}