// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using DataAccessLayer.Entity;

namespace DataAccessLayer.Context
{
    public partial class LogContext : DbContext
    {
        public LogContext()
        {
        }

        public LogContext(DbContextOptions<LogContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Log> Log { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Log>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();
            });


            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}