// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace DataAccessLayer.Entity
{
    public partial class Log
    {

        [Key]
        public long Id { get; set; }
        [Column(TypeName = "VARCHAR (50000)")]
        public string ErrorMessage { get; set; }
        [Column(TypeName = "VARCHAR (200)")]
        public string ThreadId { get; set; }       
        [Column(TypeName = "VARCHAR (50000)")]
        public string Data { get; set; }

     
    }
}