// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace DataAccessLayer.Entity
{
    public partial class Log
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long? Id { get; set; }
        [Column(TypeName = "VARCHAR (50000)")]
        public string Message { get; set; }

        [Column(TypeName = "DATETIME")]
        public DateTime CreationDate{ get { return DateTime.Now;  } }
        [Column(TypeName = "INTEGER")]
        public int Line { get; set; }
        [Column(TypeName = "VARCHAR (500)")]
        public string FileName { get; set; }       
        [Column(TypeName = "VARCHAR (50000)")]
        public string Parameters { get; set; }


    }
}