// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccessLayer.Entity
{
    public partial class Personne
    {
        [Key]
        public long Id { get; set; }
        [Column(TypeName = "VARCHAR (50)")]
        public string Nom { get; set; }
        [Column(TypeName = "VARCHAR (50)")]
        public string Prenom { get; set; }
        public long? IdAdresse { get; set; }

        [ForeignKey(nameof(IdAdresse))]
        [InverseProperty(nameof(Adresse.Personne))]
        public virtual Adresse IdAdresseNavigation { get; set; }
    }
}